IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='bank_sliver' )
BEGIN
	Alter TABLE MEMB_INFO ADD bank_sliver int NOT NULL DEFAULT 0
	PRINT 'ADDED Column MEMB_INFO.bank_sliver'
END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.bank_sliver' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='bank_sliver_lock' )
	BEGIN
		Alter TABLE MEMB_INFO ADD bank_sliver_lock int NOT NULL DEFAULT 0
		PRINT 'ADDED Column MEMB_INFO.bank_sliver_lock'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.bank_sliver_lock' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='bank_zen' )
	BEGIN
		Alter TABLE MEMB_INFO ADD bank_zen int NOT NULL DEFAULT 0
		PRINT 'ADDED Column MEMB_INFO.bank_zen'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.bank_zen' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='bank_jewel' )
	BEGIN
		Alter TABLE MEMB_INFO ADD bank_jewel int NOT NULL DEFAULT 0
		PRINT 'ADDED Column MEMB_INFO.bank_jewel'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.bank_jewel' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='point_bonus' )
	BEGIN
		Alter TABLE MEMB_INFO ADD point_bonus int NOT NULL DEFAULT 0
		PRINT 'ADDED Column MEMB_INFO.point_bonus'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.point_bonus' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='bank_jewel_lock' )
	BEGIN
		Alter TABLE MEMB_INFO ADD bank_jewel_lock int NOT NULL DEFAULT 0
		PRINT 'ADDED Column MEMB_INFO.bank_jewel_lock'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.bank_jewel_lock' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='lock_item' )
	BEGIN
		Alter TABLE Character ADD lock_item tinyint NOT NULL DEFAULT 0
		PRINT 'ADDED Column Character.lock_item'
	END
ELSE BEGIN PRINT 'Exist Column Character.lock_item' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='lock_item_code' )
	BEGIN
		Alter TABLE Character ADD lock_item_code varchar(50)
		PRINT 'ADDED Column Character.lock_item_code'
	END
ELSE BEGIN PRINT 'Exist Column Character.lock_item_code' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='point_reserve' )
	BEGIN
		Alter TABLE Character ADD point_reserve int NOT NULL DEFAULT 0
		PRINT 'ADDED Column Character.point_reserve'
	END
ELSE BEGIN PRINT 'Exist Column Character.point_reserve' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='top_0h' )
	BEGIN
		Alter TABLE Character ADD top_0h int NOT NULL DEFAULT 0
		PRINT 'ADDED Column Character.top_0h'
	END
ELSE BEGIN PRINT 'Exist Column Character.top_0h' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='Resets_Time' )
	BEGIN
		Alter TABLE Character ADD Resets_Time int NOT NULL DEFAULT 0
		PRINT 'ADDED Column Character.Resets_Time'
	END
ELSE BEGIN PRINT 'Exist Column Character.Resets_Time' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Character' AND COLUMN_NAME='Change_Class_Time' )
	BEGIN
		Alter TABLE Character ADD Change_Class_Time int NOT NULL DEFAULT 0
		PRINT 'ADDED Column Character.Change_Class_Time'
	END
ELSE BEGIN PRINT 'Exist Column Character.Change_Class_Time' END

IF NOT EXISTS ( SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='MEMB_INFO' AND COLUMN_NAME='login_token' )
	BEGIN
		Alter TABLE MEMB_INFO ADD login_token [varchar](255) NULL
		PRINT 'ADDED Column MEMB_INFO.login_token'
	END
ELSE BEGIN PRINT 'Exist Column MEMB_INFO.login_token' END